ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'MANUTENCAO';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'LIMPEZA';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'FINANCEIRO';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'SEGURANCA';
